Added hooks and added a success flag
olexale/bdd_widget_test pull request #55
Opened 2024-01-10 09:57 UTC by daniel-deboeverie-lemon

https://github.com/olexale/bdd_widget_test/issues/52

Also added a success flag to the afterEach.

2024-01-10 10:15 UTC, olexale commented
Thank you so much for this PR, I'll review it during the weekend 🙏

@lsaudon, you might want to check this out too as you proposed this functionality in the first place 🙂

2024-01-10 18:50 UTC, lsaudon approved these changes
Great job.
Thanks for making the pull request linked to my issue.

2024-01-14 15:42 UTC, olexale requested changes
Thank you so much for the PR one more time. I've added a few propositions, would you mind to review?

2024-01-14 15:42 UTC, olexale commented on lib/src/generator_options.dart
> +    enableHooks: doc['hookImportLine'] as bool?,
Shouldn't it be `doc['addHooks'] as bool?` ?

2024-01-14 15:42 UTC, olexale commented on lib/src/generator_options.dart
> +  final bool enableHooks;
Please either rename the property to `addHooks` or change the name in the configuration file.

2024-01-14 15:42 UTC, olexale commented on lib/src/generator_options.dart
> +        enableHooks: json['enableHooks'] as bool?,
Shouldn't `hookFolderName` be here?

2024-01-14 15:42 UTC, olexale commented on lib/src/generator_options.dart
> +    enableHooks: doc['hookImportLine'] as bool?,
Shouldn't `hookFolderName` be here too?

2024-01-14 15:42 UTC, olexale commented on lib/src/generator_options.dart
> +      enableHooks: a.enableHooks != false ? a.enableHooks : b.enableHooks,
Shouldn't `hookFolderName` be here also?

2024-01-14 15:42 UTC, olexale commented on lib/src/hook_file.dart
> +  HookFile._create({
```suggestion
  const HookFile._create({
```

2024-01-14 15:42 UTC, olexale commented on lib/src/hook_file.dart
> +  static HookFile create({
There is a linter warning here. It might be fixed like that:
```suggestion
  factory HookFile.create({
```

2024-01-14 15:42 UTC, olexale commented on README.md
> +          addHooks: true
```suggestion
          enableHooks: true
```

2024-01-14 15:42 UTC, olexale commented on lib/src/hook_file.dart
> +}
I guess class is highly optional, but if you think it is needed, please make it abstract with private a constructor. It is better to replace `dynamic`s with proper `Future<void>` or `FutureOr<void>` types, some users might have [this rule](https://dart.dev/tools/linter-rules/prefer_function_declarations_over_variables) enabled, hence it is better to declare functions as functions.

```suggestion
import 'dart:async';

abstract class Hooks {
  const Hooks._();

  static FutureOr<void> beforeEach(String title, [List<String>? tags]) {
    // Add logic for beforeEach
  }

  static FutureOr<void> beforeAll() {
    // Add logic for beforeAll
  }

  static FutureOr<void> afterEach(
    String title,
    bool success, [
    List<String>? tags,
  ]) {
    // Add logic for afterEach
  }

  static FutureOr<void> afterAll() {
    // Add logic for afterAll
  }
}
```

2024-01-14 15:42 UTC, olexale commented on lib/src/scenario_generator.dart
> +        sb.writeln('        ${tagsToString(tags)},');
```suggestion
      sb.writeln('          '''$scenarioTitle''',');
      sb.writeln('          $testSuccessVariableName,');
      if (tags.isNotEmpty) {
        sb.writeln('          ${tagsToString(tags)},');
```

2024-01-14 15:42 UTC, olexale commented on lib/src/scenario_generator.dart
> +      '${spaces}await $setUpHookName("$scenarioTitle" ${tags.isNotEmpty ? ', ${tagsToString(tags)}' : ''});',
It is unsafe assumption that users aren't using quotes in scenario titles, please use `'''` here and in other places.
```suggestion
      '${spaces}await $setUpHookName('''$scenarioTitle''' ${tags.isNotEmpty ? ', ${tagsToString(tags)}' : ''});',
```

2024-01-14 15:42 UTC, olexale commented on lib/src/feature_file.dart
> +      : null;
With this approach, the `hookFile` property will be calculated each time it is accessed. Please make it a property
```dart
final HookFile? hookFile;
```
and initialize it in the constructor, like:
```dart
  })  : _lines = _prepareLines(
          input.split('\n').map((line) => line.trim()).map(BddLine.new),
        ),
        hookFile = generatorOptions.enableHooks
            ? HookFile.create(
                featureDir: featureDir,
                package: package,
                generatorOptions: generatorOptions,
              )
            : null {
```

2024-01-16 17:15 UTC, olexale commented
Hey @daniel-deboeverie-lemon,
Thanks for all changes you've made to the PR. It looks great already, but CI spot a few missing tests. Would you please add them? I'll try to find some time during the weekend if you would not add them earlier.

2024-01-20 12:29 UTC, olexale approved these changes

2024-01-20 12:29 UTC, merged

2024-01-20 12:30 UTC, olexale commented
Thanks again for the PR, I've added missing tests. I'll publish a new version once I merge the other opened PR (hopefully, soon).